"""
JALAAKAR — application database (users, subscriptions, alert log).

WHY THIS IS A SEPARATE FILE FROM jalaakar.db
--------------------------------------------
`data/jalaakar.db` is *derived*. Every row in it can be regenerated by re-running
the ingest scripts, and it gets rebuilt, frozen and copied routinely — the
Data Ingestion session dropped and reloaded `reservoir_daily` twice in one
evening. Signups cannot live somewhere that gets dropped.

So user-generated data lives in `data/app.db`, which nothing in `ingest/` ever
touches. Pipeline data is reproducible; user data is not. Keep them apart.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import re
import secrets
import sqlite3
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# WHERE app.db LIVES IS A DEPLOYMENT DECISION, NOT A SOURCE-CODE ONE.
#
# Locally this is data/app.db and stays that way. On a host, data/ sits inside
# the deployed image, and an image is replaced wholesale on every deploy — so a
# signup made on Tuesday is gone after Wednesday's push, with nothing logged
# and nobody told. The fix is to point this at a volume that outlives the
# image, which is a per-host path, which means an environment variable.
#
# Unset, the behaviour is exactly what it was before.
APP_DB = Path(os.environ.get("JALAAKAR_APP_DB") or (ROOT / "data" / "app.db"))
APP_DB.parent.mkdir(parents=True, exist_ok=True)

PIPELINE_DB = ROOT / "data" / "jalaakar.db"

SCHEMA = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    user_id       TEXT PRIMARY KEY,
    role          TEXT NOT NULL,      -- farmer|society-manager|society-resident|government
    name          TEXT NOT NULL,
    phone_e164    TEXT NOT NULL,      -- +91XXXXXXXXXX, normalised on write
    pw_hash       TEXT,               -- pbkdf2_sha256$iters$salt$hash, NULL for
                                      -- accounts created before passwords
    lang          TEXT NOT NULL,      -- mr|hi|en
    place_raw     TEXT NOT NULL,      -- exactly what they typed
    entity_type   TEXT,               -- well|reservoir|taluka|unresolved
    entity_id     TEXT,               -- resolved target we forecast against
    entity_label  TEXT,               -- human-readable, echoed to the dashboard
    verified      INTEGER NOT NULL DEFAULT 0,   -- govt accounts need approval
    created_at    TEXT NOT NULL,
    UNIQUE (phone_e164),
    CHECK (role IN ('farmer','society-manager','society-resident','government')),
    CHECK (lang IN ('mr','hi','en'))
);
CREATE INDEX IF NOT EXISTS idx_users_entity ON users(entity_type, entity_id);

-- Every outbound message, whether it was really sent or only rendered.
-- `channel='console'` is the honest record of a demo that did not touch
-- Twilio; do not delete these rows to make the log look better.
CREATE TABLE IF NOT EXISTS alert_log (
    alert_id     TEXT PRIMARY KEY,
    user_id      TEXT REFERENCES users(user_id) ON DELETE CASCADE,
    created_at   TEXT NOT NULL,
    channel      TEXT NOT NULL,       -- whatsapp|console
    lang         TEXT NOT NULL,
    score        INTEGER,
    band         TEXT,
    days_to_crisis INTEGER,
    body         TEXT NOT NULL,
    status       TEXT NOT NULL,       -- sent|failed|rendered
    provider_sid TEXT,
    error        TEXT
);
CREATE INDEX IF NOT EXISTS idx_alert_user ON alert_log(user_id, created_at);
"""


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


@contextmanager
def app_db():
    APP_DB.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(APP_DB)
    con.row_factory = sqlite3.Row
    try:
        # WAL is better under concurrent reads, but it needs shared-memory
        # mmap, which some filesystems (network shares, container bind mounts)
        # cannot provide — there it fails with a bare "disk I/O error" that
        # looks like data corruption. Try it, fall back quietly if unavailable.
        try:
            con.execute("PRAGMA journal_mode = WAL")
        except sqlite3.OperationalError:
            con.execute("PRAGMA journal_mode = DELETE")
        con.executescript(SCHEMA)
        migrate(con)
        yield con
        con.commit()
    finally:
        con.close()


@contextmanager
def pipeline_db():
    """Read-only. The API must never write to the derived database."""
    if not PIPELINE_DB.exists():
        raise FileNotFoundError(
            f"{PIPELINE_DB} not found — run the ingest pipeline first")
    con = sqlite3.connect(f"file:{PIPELINE_DB}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    try:
        yield con
    finally:
        con.close()


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


def migrate(con) -> None:
    """Add columns that arrived after the first accounts did.

    Existing installs already have a users table without pw_hash. A bare
    CREATE TABLE IF NOT EXISTS will not add it, and the first login would
    then fail with 'no such column' on someone's laptop and not on mine.
    """
    cols = {r[1] for r in con.execute("PRAGMA table_info(users)")}
    if cols and "pw_hash" not in cols:
        con.execute("ALTER TABLE users ADD COLUMN pw_hash TEXT")
        print("[appdb] migrated: users.pw_hash added")


# --------------------------------------------------------------------------
# Passwords. PBKDF2-HMAC-SHA256 from the standard library — no bcrypt, no
# argon2, nothing to pip install on demo day. 240k iterations is the current
# OWASP floor for PBKDF2-SHA256.
#
# Not a substitute for a real auth service; it is a real hash rather than a
# stored plaintext, which is the part that actually matters here.
# --------------------------------------------------------------------------
PBKDF2_ITERS = 240_000
MIN_PASSWORD = 8


def hash_password(pw: str) -> str:
    if len(pw or "") < MIN_PASSWORD:
        raise ValueError(f"Password must be at least {MIN_PASSWORD} characters.")
    salt = secrets.token_hex(16)
    dk = hashlib.pbkdf2_hmac("sha256", pw.encode(), bytes.fromhex(salt),
                             PBKDF2_ITERS)
    return f"pbkdf2_sha256${PBKDF2_ITERS}${salt}${dk.hex()}"


def verify_password(pw: str, stored: str | None) -> bool:
    if not stored or not pw:
        return False
    try:
        algo, iters, salt, want = stored.split("$")
        if algo != "pbkdf2_sha256":
            return False
        dk = hashlib.pbkdf2_hmac("sha256", pw.encode(), bytes.fromhex(salt),
                                 int(iters))
    except (ValueError, TypeError):
        return False
    # constant time — a length-independent compare leaks the prefix
    return hmac.compare_digest(dk.hex(), want)


# --------------------------------------------------------------------------
def normalise_phone(raw: str) -> str:
    """Indian mobile -> E.164. Must stay in lockstep with validatePhone in
    web/script.js — if they disagree, a number that passes in the browser
    fails at the API, which is a miserable bug to chase.

    Strip the country code by LENGTH, never by prefix. `91` is a real Indian
    mobile prefix as well as the country code, so the obvious
    `re.sub(r"^(0?91|0)", "", digits)` turns a valid 9123456780 into an
    8-digit string and rejects it. Only remove 91 when what remains is
    still a full 10-digit number.
    """
    digits = re.sub(r"\D", "", raw or "")

    if len(digits) == 13 and digits.startswith("091"):
        local = digits[3:]
    elif len(digits) == 12 and digits.startswith("91"):
        local = digits[2:]
    elif len(digits) == 11 and digits.startswith("0"):
        local = digits[1:]
    else:
        local = digits

    if len(local) != 10 or not re.match(r"^[6-9]", local):
        raise ValueError("Enter a 10-digit Indian mobile number.")
    return f"+91{local}"
